### PR TITLE
Import GCP plugin to prevent controller startup failures in GKE

### LINKED ISSUE #31: EtcdProxy Controller deployment doesn't work in GKE
When deploying the controller using [the deployment manifest](https://github.com/xmudrii/etcdproxy-controller/blob/master/artifacts/deployment/00-etcdproxy-controller.yaml), `kubectl` returns the permission errors when trying to create [the `etcdproxy-crd-clusterrole` ClusterRole](https://github.com/xmudrii/etcdproxy-controller/blob/master/artifacts/deployment/00-etcdproxy-controller.yaml#L23-L34) and [the `etcdproxy-controller-role` Role](https://github.com/xmudrii/etcdproxy-controller/blob/master/artifacts/deployment/00-etcdproxy-controller.yaml#L36-L51).

The docs should be updated to mention that when running in GKE, your current IAM user must be the cluster-admin. Instrunctions for making your IAM user a cluster-admin can be found in [the Role Based Access Control portion of the Google docs](https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#prerequisites_for_using_role-based_access_control).

Also, we need to verify is the controller able to authenticate when running in-cluster, because in some cases, it's required to import the GCP plugin ([example from the `sample-controller`](https://github.com/kubernetes/sample-controller/blob/master/main.go#L27-L28)).

### PR DESCRIPTION
**Pull request by xmudrii**
Running the EtcdProxy Controller on GKE returns errors, as we're depending on in-cluster authorization, which in case of GKE/GCP requires the GCP authorization plugin.

The error I'm getting before importing the plugin:
```
F0709 02:41:29.896750   10597 start.go:38] No Auth Provider found for name "gcp"
exit status 255
```

After importing the GCP plugin, controller seems to work as intended:
```
I0709 02:43:44.236732   10821 etcdproxy_controller.go:119] Setting up event handlers
I0709 02:43:44.236892   10821 etcdproxy_controller.go:176] Starting EtcdStorage controller
I0709 02:43:44.236908   10821 etcdproxy_controller.go:179] Waiting for informer caches to sync
I0709 02:43:44.537387   10821 etcdproxy_controller.go:184] Starting workers
I0709 02:43:44.537429   10821 etcdproxy_controller.go:190] Started workers
```

Along with #42, this PR closes #31.

/cc @deads2k @sttts

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -7,6 +7,7 @@ import (
 	"github.com/xmudrii/etcdproxy-controller/pkg/cmd/controller"
 	"github.com/xmudrii/etcdproxy-controller/pkg/signals"
 	"k8s.io/apiserver/pkg/util/logs"
+	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
```
Comment (sttts) [inline main.go]: add a comment above every _ import

**Comment by sttts** [comment]
After the comment, lgtm.
